---
title: "week7-quiz"
author: "Bruno Seo"
date: "7/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# 1
# While simple linear model includes both sexes, if includes female
library(MASS)
simpleModel = lm(Hwt ~ Bwt, data = cats)
coef(simpleModel)[2]
```

```{r}
# 2
interactionModel = lm(Hwt ~ Bwt * originSex, data = cats)
coef(interactionModel)[2]
```

```{r}
# 3
interactionModel = lm(Hwt ~ Bwt * originSex, data = cats)
coef(interactionModel)[2] + coef(interactionModel)[4]
```

```{r}
# 4
# This is just 0. Addictive model shares the same slope beteween differe t categories.
```

```{r}
# 5
anova(addictiveModel, interactionModel)$F[2]
```

```{r}
# 6
anova(addictiveModel, interactionModel)
```

```{r}
# 7
iris_add = lm(Sepal.Length ~ Petal.Length + Species, data = iris)
predict(iris_add, newdata = data.frame(Petal.Length = 5.10, Species = 'versicolor'))

```

```{r}
# 8
iris_add = lm(Sepal.Length ~ Petal.Length + Species, data = iris)
unique(iris$Species)
coef(iris_add)
confint(iris_add, level=.9)
confint(iris_add, level=.9)[4,1]

```

```{r}
# 9
iris_null = lm(Sepal.Length ~ Petal.Length, data = iris)
iris_add  = lm(Sepal.Length ~ Petal.Length + Species, data = iris)

anova(iris_null, iris_add)$'F'[2]
```

```{r}
# 10
iris_int = lm(Sepal.Length ~ Petal.Length * Species, data = iris)
length(coef(iris_int))

```

```{r}
# 11
iris_int = lm(Sepal.Length ~ Petal.Length * Species, data = iris)
predict(iris_int, level = .99, interval = 'prediction', newdata = data.frame(Petal.Length = 5.10, Species = 'versicolor'))
predict(iris_int, level = .99, interval = 'prediction', newdata = data.frame(Petal.Length = 5.10, Species = 'versicolor'))[3]

```

```{r}
# 12
iris_int = lm(Sepal.Length ~ Petal.Length * Species, data = iris)
coef(iris_int)
coef(iris_int)[2] + coef(iris_int)[5]
```

```{r}
# 13
anova(iris_add, iris_int)
```

```{r}
# 14
swiss_model = lm(Fertility ~ Education*Catholic*Infant.Mortality, data=swiss)

coef(swiss_model)

coef(swiss_model)[2] + 90*coef(swiss_model)[5] + 20*coef(swiss_model)[6] + 90*20*coef(swiss_model)[8]

```

```{r}
# 15
swiss_null_model = lm(Fertility ~ Education*Catholic + Catholic*Infant.Mortality + Infant.Mortality*Education, data=swiss)
anova(swiss_null_model, swiss_model)
anova(swiss_null_model, swiss_model)$'Pr(>F)'[2]
```











