---
title: "w04-quiz4"
author: "Bruno Seo"
date: "6/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# 1
pf(2.4, 9, 30-10, lower.tail = FALSE)
```


```{r}
# 2
pt(-1.3, 20-6) * 2
```


```{r}
# 3
set.seed(42)
x_values = data.frame(
  x1 = runif(15),
  x2 = runif(15),
  x3 = runif(15)
)

X = cbind(1, x_values$x1, x_values$x2, x_values$x3)
C = solve(t(X) %*% X)
3 * sqrt(C[3,3])
```

```{r}
# 4
swiss
model = lm(Fertility ~ ., data=swiss)
predict(model, newdata=data.frame(Agriculture = 54,
                                  Examination = 23,
                                  Education = 13,
                                  Catholic = 60,
                                  Infant.Mortality = 24))
```

```{r}
# 5
confint(model, level=.99)['Catholic', 2]
```

```{r}
# 6
coef(summary(model))
coef(summary(model))['Examination', 4]
```

```{r}
# 7
predict(model, newdata = data.frame(Agriculture = 40,
                                  Examination = 28,
                                  Education = 10,
                                  Catholic = 42,
                                  Infant.Mortality = 27),
        level=.95, interval="confidence")[2]
```

```{r}
# 8
predict(model, newdata = data.frame(Agriculture = 40,
                                  Examination = 28,
                                  Education = 10,
                                  Catholic = 42,
                                  Infant.Mortality = 27),
        level=.95, interval="prediction")[2]
```

```{r}
# 9
summary(model)$fstatistic[1]
```

```{r}
# 10
summary(model)
```

```{r}
# 11
null = lm(Fertility ~ Education + Catholic + Infant.Mortality, data=swiss)
anova(null, model)
anova(null, model)$'Pr(>F)'[2]
```

```{r}
# 12
# 0.8
```

```{r}
# 13
# Not enough info
```

```{r}
# 14
# None of the above
```


```{r}
# 15
# could be greater than
```


