---
title: "stat420-week4-quiz"
author: "Bruno Seo"
date: "6/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# 1
p = 10
n = 30
pf(2.4, p-1, n-p, lower.tail = FALSE)
# 1st attempt pf(2.4, p-1, n-p, lower.tail = FALSE) *2
# 2nd attempt
```

```{r}
# 2
p = 6
n = 20
pt(-1.3, n-p) * 2
```

```{r}
# 3
set.seed(42)
x_values = data.frame(
  x1 = runif(15),
  x2 = runif(15),
  x3 = runif(15)
)
X = cbind(1, x_values$x1, x_values$x2, x_values$x3)
cov = solve(t(X) %*% X)
3 * sqrt(cov)
3 * sqrt(cov)[3,3]
```

```{r}
# 4
swiss_model = lm(Fertility ~ ., data=swiss)
predict(swiss_model, newdata = data.frame(Agriculture = 54,
                                           Examination = 23,
                                           Education = 13,
                                           Catholic = 60,
                                           Infant.Mortality = 24))
```



```{r}
# 5
confint(swiss_model,level=.99)
confint(swiss_model, parm = "Catholic" ,level=.99)[2]
```



```{r}
# 6
coef(summary(swiss_model))
coef(summary(swiss_model))["Examination", "Pr(>|t|)"]
```


```{r}
# 7
swiss_model = lm(Fertility ~ . , data = swiss)
predict(swiss_model, newdata = data.frame(Agriculture = 40,
                                          Examination = 28,
                                          Education = 10,
                                          Catholic = 42,
                                          Infant.Mortality = 27),
                    interval = "confidence", level=.95)

predict(swiss_model, newdata = data.frame(Agriculture = 40,
                                          Examination = 28,
                                          Education = 10,
                                          Catholic = 42,
                                          Infant.Mortality = 27),
                    interval = "confidence", level=.95)[,"lwr"]
```




```{r}
# 8

predict(swiss_model, newdata = data.frame(Agriculture = 40,
                                          Examination = 28,
                                          Education = 10,
                                          Catholic = 42,
                                          Infant.Mortality = 27),
                    interval = "prediction", level=.95)[,"lwr"]


```



```{r}
# 9
summary(swiss_model)
summary(swiss_model)$fstatistic[1]
```


```{r}
# 10
# alpha > p-value
# reject h_0

```



```{r}
# 11

nested_model = lm(Fertility ~ Education + Catholic +  Infant.Mortality, data=swiss)
full_model = lm(Fertility ~ ., data=swiss)

(anv = anova(nested_model, full_model))
anv$"Pr(>F)"[2]
```


```{r}
# 12
# The model with 0.8
```


```{r}
# 13
# P-value for testing b_1 will be larger than b_2
# 2nd attempt 3
```


```{r}
# 14
# differnt, but still positive 
# 
```



```{r}
# 15
# H_0: b_1 = 0, if b_2 = 0 has a p-value greater than 0.01
```









