---
title: "midterm"
author: "Bruno Seo"
date: "6/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# 1
set.seed(43)
x = rnorm(250, 2, sd=sqrt(10))

length(x[x>5]) / 250
```


```{r}
# 2

some_fun = function(arg1 = 2, arg2 = 1) {
  mean(arg2) * arg1
}

  
(some_fun() + some_fun(arg1 = 3, arg2 = 1:10)) / some_fun(arg1 = 5, arg2 = 1:5)
```


```{r}
# 3
trees
?trees

model = lm(Volume ~ Height, data=trees)
summary(model)
summary(model)$r.squared
```


```{r}
# 4
Orange
?Orange
model = lm(circumference ~ age, data=Orange)
range(Orange$age)
predict(model, newdata=data.frame(age=c(400, 2500)))[1]
```


```{r}
# 5
df = data.frame(circumference = Orange$circumference,
                age = Orange$age + 1)
model = lm(circumference ~ age, data=df)
confint(model, level=.99)
confint(model, level=.99)[2,2]

```


```{r}
# 6
model = lm(circumference ~ age, data=Orange)
predict(model, newdata=data.frame(age=250), level=.90, interval="confidence")
```


```{r}
# 7
model = lm(circumference ~ age, data=Orange)
predict(model, newdata=data.frame(age=500), level=.95, interval="prediction")[2]

```


```{r}
# 8
model = lm(circumference ~ age, data=Orange)
coef(summary(model))
SE = coef(summary(model))[2,2]
beta_1_hat = coef(summary(model))[2,1]
t = (beta_1_hat - 0.125) / SE

n = length(Orange$age)

pt(t, n-2) * 2
```


```{r}
# 9
pnorm(5 ,3, sd=3)
```


```{r}
# 10
m = 4 + 1.3*1 + -2.4*2 + 3.7*3
pnorm(13 , m, sd=5, lower.tail=FALSE)
```


```{r}
# 11
set.seed(420)
x_values = data.frame(
  x1 = rnorm(15),
  x2 = runif(15),
  x3 = runif(15),
  x4 = runif(15)
)

X = cbind(1, x_values$x1, x_values$x2, x_values$x3, x_values$x4)
C = solve(t(X) %*% X)
sigma = 5
SD_beta_1_hat = 5 * sqrt(C)
SD_beta_1_hat[2,2]
```


```{r}
# 12
qt(0.01/2, 17-7, lower.tail=FALSE)
```


```{r}
# 13
library(MASS)
b_model = lm(medv ~ rm + crim, data=Boston)
summary(b_model)$r.squared
```


```{r}
# 14
b_model = lm(medv ~ lstat + rm + crim + tax + nox, data=Boston)
summary(b_model)
coef(summary(b_model))[6,4]
anova(b_model)['nox','Pr(>F)']
```


```{r}
# 15
full_model = lm(medv ~ rm + crim + tax + nox, data=Boston)
null_model = lm(medv ~ rm + nox, data=Boston)
anova(null_model, full_model)
anova(null_model, full_model)$RSS[2]

# reject h_0

```
